### ISSUE TITLE
Microphone problem

### ISSUE THREAD

**Issue by acl61582** [Herring-UGAECSE-2920-S22/Class-Instructions#9]
We seemed to set up the microphone circuit correctly, but we are not getting the desired graph when running analysis on the oscilloscope. The graph we are receiving is attaching below.
![image](https://user-images.githubusercontent.com/97557629/150240499-f3439bd1-b8f5-4b3c-b924-4559794984ad.png)

**Comment by fisch-vic** [comment]
I think some confusing instructions were given in class on Wednesday.

That set of instructions is for analyzing a filter or another circuit with an electrical input. Since the microphone has an acoustic input, you need to test it with an acoustic source. That's why Herring mentioned using a signal generator app on your phone. You should connect the output of the microphone module to a channel on the scope. Then start the FFT analysis on the scope. You can find it in the "Math" menu by hitting the Math button & spinning the selector knob to pick FFT. 

You'll have to adjust the parameters to center the window around whichever frequency your generating on your phone. You should be able to see the spike on the plot.
